
- block:
  - name: include system specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "basesys/{{ ansible_system }}.yml"
        skip: true

  - name: include OS family version specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "basesys/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        skip: true

  - name: include OS family specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "basesys/{{ ansible_os_family }}.yml"
        skip: true

  - name: include OS distribution specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - files:
        - "basesys/{{ ansible_distribution }}.yml"
        skip: true

  tags:
    - always

- include_tasks: proxy.yml
- include_tasks: packages.yml
- include_tasks: timezone.yml
- include_tasks: ntp.yml
- include_tasks: ssh.yml
- include_tasks: groups.yml
- include_tasks: users.yml
- include_tasks: guest.yml
- include_tasks: disk.yml
