
- block:

  - name: include ntp tasks
    include: "{{ basesys_ntp_include }}"
    with_first_found:
      - "ntp/{{ ansible_os_family }}.yml"
      - "ntp/{{ ansible_system }}.yml"
      - "ntp/default.yml"
    loop_control:
      loop_var: basesys_ntp_include

  when:
    - basesys_ntp != false
    - basesys_ntp != None
  tags:
    - basesys
    - basesys_ntp
