
- block:

  - name: build group index
    set_fact:
      basesys_group: "{{ basesys_group | d({}) | combine({item.name: item}) }}"
    with_items:
      - "{{ basesys_groups }}"
      - "{{ basesys_local_groups | d([]) }}"

  - debug: var=basesys_group

  - name: create groups
    group:
      name: "{{ item.name }}"
      gid: "{{ item.gid | d(omit) }}"
      state: "{{ item.state | d(omit) }}"
      system: "{{ item.system | d(omit) }}"
    with_items: "{{ basesys_groups }}"

  - name: add sudoers template
    ansible.builtin.template:
      src: "templates/sudoers.j2"
      dest: "{{ basesys_sudoers_d }}/{{ item.name }}"
      mode: 0440
    when:
      - sudo_as_doas is defined and sudo_as_doas == false or sudo_as_doas is not defined
      - item.sudo is defined
      - item.sudo != false
      - item.sudo != None 
    loop: "{{ basesys_groups }}"
  
  - name: add doas template
    ansible.builtin.template:
      src: "templates/doas.conf.j2"
      dest: "{{ basesys_doas_conf }}"
      mode: 0440
    when:
      - sudo_as_doas is defined and sudo_as_doas != false
      - item.sudo is defined
      - item.sudo != false
      - item.sudo != None 
    loop: "{{ basesys_groups }}"

  when:
    - basesys_groups != false
    - basesys_groups != None
  tags:
    - basesys
    - basesys_groups
