
- block:
  - name: install packages
    package: name={{item}} state={{basesys_ntp_package_state}}
    with_items: "{{basesys_ntp_packages}}"
    when: basesys_ntp_packages | length > 0

  - name: enable service
    service: name={{basesys_ntp_service}}
             enabled=yes
             state=started
    notify: basesys set current time
    when:
      - basesys_ntp_service != false
      - basesys_ntp_service != None

  - name: set ntp servers
    lineinfile:
      dest: "{{ basesys_ntp_config_file }}"
      regexp: '^server {{ item }}(\s|$)'
      line: "server {{ item }}{% if basesys_ntp_server_options %} {{ basesys_ntp_server_options | join(' ')}}{% endif %}"
      insertafter: "^server "
      create: no
      owner: root
      group: root
      mode: 0644
    with_items:
      - "{{basesys_ntp_servers}}"
    when:
      - basesys_ntp_service != false
      - basesys_ntp_service != None

  # this comes after set so it doesn't move servers location in the file
  - name: remove other ntp servers
    lineinfile:
      dest: "{{ basesys_ntp_config_file }}"
      regexp: "{{ basesys_ntp_servers | bsysf_ntp_server_regex(basesys_ntp_server_options) }}"
      state: absent
    when:
      - basesys_ntp_service != false
      - basesys_ntp_service != None

  when:
    - basesys_ntp != false
    - basesys_ntp != None
